import React, { useState, useEffect } from 'react';
import Modal from './ui/Modal.tsx';
import type { Eepsite } from '../types';
import { initializeGitForNewEepsite } from '../utils/git.ts';

interface HostEepsiteModalProps {
    eepsiteToEdit?: Eepsite;
    onClose: () => void;
    onSave: (eepsite: Eepsite, openEditor: boolean) => void;
}

const InfoIcon = ({ className = "h-4 w-4" }) => <svg xmlns="http://www.w.3.org/2000/svg" className={className} fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}><path strokeLinecap="round" strokeLinejoin="round" d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z" /></svg>;

const defaultIndexHtml = `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>My New I2P Site</title>
    <style>
        body { font-family: sans-serif; background: #111827; color: #d1d5db; display: flex; justify-content: center; align-items: center; height: 100vh; margin: 0; }
        .container { text-align: center; }
        h1 { color: #a78bfa; }
    </style>
</head>
<body>
    <div class="container">
        <h1>Welcome to your new Eepsite!</h1>
        <p>This site was generated by the Echelon PWA.</p>
        <p>You can now edit this <code>index.html</code> file in the code editor.</p>
    </div>
</body>
</html>`;


const HostEepsiteModal: React.FC<HostEepsiteModalProps> = ({ eepsiteToEdit, onClose, onSave }) => {
    const [name, setName] = useState('');
    const [directory, setDirectory] = useState('');

    useEffect(() => {
        if (eepsiteToEdit) {
            setName(eepsiteToEdit.name.replace('.i2p', ''));
            setDirectory(eepsiteToEdit.localDirectory);
        }
    }, [eepsiteToEdit]);

    const handleSave = () => {
        // If editing, require fields.
        if (eepsiteToEdit && (!name.trim() || !directory.trim())) {
             alert('Please fill in both site name and directory.');
            return;
        }

        // If creating a new site from scratch
        if (!eepsiteToEdit && !name.trim() && !directory.trim()) {
            const randomWords = ['aurora', 'cascade', 'nebula', 'photon', 'quasar', 'rift', 'vector'];
            const randomName = `${randomWords[Math.floor(Math.random() * randomWords.length)]}-${randomWords[Math.floor(Math.random() * randomWords.length)]}-${Math.floor(Math.random() * 1000)}`;
            const files = {
                'index.html': { content: defaultIndexHtml }
            };
            const newSite: Eepsite = {
                id: `eepsite_${Date.now()}`,
                name: `${randomName}.i2p`,
                localDirectory: `[in-browser-editor]`,
                status: 'Offline',
                createdAt: new Date(),
                files,
                git: initializeGitForNewEepsite(files),
            };
            onSave(newSite, true); // Save and open editor
            return;
        }

        // If creating a new site with fields filled
        const baseFiles = eepsiteToEdit?.files || { 'index.html': { content: defaultIndexHtml } };
        const savedEepsite: Eepsite = {
            id: eepsiteToEdit?.id || `eepsite_${Date.now()}`,
            name: `${name.trim()}.i2p`,
            localDirectory: directory.trim(),
            status: eepsiteToEdit?.status || 'Offline',
            createdAt: eepsiteToEdit?.createdAt || new Date(),
            files: baseFiles,
            git: eepsiteToEdit?.git || initializeGitForNewEepsite(baseFiles),
        };
        onSave(savedEepsite, false); // Just save
    };

    return (
        <Modal title={eepsiteToEdit ? 'Edit Eepsite' : 'Host New Eepsite'} onClose={onClose}>
            <div className="space-y-4">
                 {!eepsiteToEdit && (
                    <div className="p-3 bg-slate-700/50 border border-slate-700 rounded-lg text-sm flex items-start gap-2">
                        <InfoIcon className="h-5 w-5 text-blue-400 flex-shrink-0 mt-0.5" />
                        <p className="text-gray-300">
                            <span className="font-semibold">Quick Start:</span> Leave the fields blank and click "Host Site" to generate a new site and open the in-browser code editor.
                        </p>
                    </div>
                )}
                <div>
                    <label className="text-sm text-gray-400 block mb-1">Site Name</label>
                    <div className="flex items-center">
                        <input
                            type="text"
                            value={name}
                            onChange={(e) => setName(e.target.value.replace(/[^a-z0-9-]/gi, ''))}
                            placeholder="my-cool-site"
                            className="w-full bg-slate-700 text-white p-3 rounded-l-lg border border-slate-600 focus:ring-purple-500 focus:border-purple-500 font-mono"
                        />
                        <span className="bg-slate-700 text-gray-400 p-3 rounded-r-lg border border-l-0 border-slate-600 font-mono">.i2p</span>
                    </div>
                </div>
                 <div>
                    <label className="text-sm text-gray-400 block mb-1">Local Directory Path</label>
                    <input
                        type="text"
                        value={directory}
                        onChange={(e) => setDirectory(e.target.value)}
                        placeholder="/path/to/your/site"
                        className="w-full bg-slate-700 text-white p-3 rounded-lg border border-slate-600 focus:ring-purple-500 focus:border-purple-500 font-mono"
                    />
                     <p className="text-xs text-gray-500 mt-1">Provide the full path to the directory containing your site's files (e.g., index.html).</p>
                </div>
                <div className="pt-4 flex flex-col sm:flex-row gap-4">
                    <button 
                        onClick={onClose}
                        className="flex-1 bg-slate-600 hover:bg-slate-700 text-white font-semibold py-3 px-4 rounded-lg transition-colors"
                    >
                        Cancel
                    </button>
                    <button
                        onClick={handleSave}
                        className="flex-1 bg-purple-600 hover:bg-purple-700 text-white font-semibold py-3 px-4 rounded-lg transition-colors"
                    >
                        {eepsiteToEdit ? 'Save Changes' : 'Host Site'}
                    </button>
                </div>
            </div>
        </Modal>
    );
};

export default HostEepsiteModal;